### ISSUE TITLE
Do you mean to host this directly on github?

### ISSUE THREAD

**Issue by TheZorcerer** [TMcSquared/MyWebsite#1]
I'm just checking if you know about github pages: https://pages.github.com/
Or are you hosting it somewhere else?
Sorry to disturb, but I thought you should know about this.

**Comment by TMcSquared** [comment]
@TheZorcerer Hey man, long time no speak! Yeah, I'm probably gonna do that eventually, but I need to do some polishing and reconfigurations first.
